/**
 * Infrastructure: DotEnvCredentialsManager
 * Manages credentials using .env files
 */

import * as path from 'node:path';
import { injectable, inject } from 'tsyringe';
import { ICredentialsManager, Credentials, CredentialValidationResult } from '../domain/ICredentialsManager';
import { IFileSystem } from '@/shared/infrastructure/file-system/IFileSystem';

/**
 * DotEnvCredentialsManager
 * Stores credentials in .env files next to config files
 *
 * SOLID Principles:
 * - SRP: Only responsible for .env file operations
 * - DIP: Depends on IFileSystem interface
 */
@injectable()
export class DotEnvCredentialsManager implements ICredentialsManager {
  constructor(@inject('IFileSystem') private readonly fileSystem: IFileSystem) {}

  async saveCredentials(configPath: string, credentials: Credentials): Promise<string> {
    const envPath = this.getCredentialsPath(configPath);

    // Ensure directory exists
    const dir = path.dirname(envPath);
    await this.fileSystem.ensureDir(dir);

    // Convert credentials to .env format
    const envContent = this.credentialsToEnvFormat(credentials);

    // Write to file
    await this.fileSystem.writeFile(envPath, envContent);

    return envPath;
  }

  async loadCredentials(configPath: string): Promise<Credentials> {
    const envPath = this.getCredentialsPath(configPath);

    // Check if file exists
    const exists = await this.fileSystem.exists(envPath);
    if (!exists) {
      return {};
    }

    // Read file
    const content = await this.fileSystem.readFile(envPath);

    // Parse .env format
    return this.parseEnvFormat(content);
  }

  async credentialsExist(configPath: string): Promise<boolean> {
    const envPath = this.getCredentialsPath(configPath);
    return this.fileSystem.exists(envPath);
  }

  async validateCredentials(
    configPath: string,
    requiredFields: string[]
  ): Promise<CredentialValidationResult> {
    const credentials = await this.loadCredentials(configPath);
    const presentFields = Object.keys(credentials);
    const missingFields = requiredFields.filter(field => !(field in credentials));

    return {
      isValid: missingFields.length === 0,
      missingFields,
      presentFields,
    };
  }

  getCredentialsPath(configPath: string): string {
    const dir = path.dirname(configPath);
    const baseName = path.basename(configPath, path.extname(configPath));

    // Use format: .env.mcp-<client-name>
    // E.g., for claude_desktop_config.json -> .env.mcp-claude-desktop
    const envFileName = `.env.mcp-${baseName.replace(/_/g, '-').replace(/config/gi, '').replace(/--+/g, '-').replace(/^-|-$/g, '')}`;

    return path.join(dir, envFileName);
  }

  async deleteCredentials(configPath: string): Promise<void> {
    const envPath = this.getCredentialsPath(configPath);
    const exists = await this.fileSystem.exists(envPath);

    if (exists) {
      // Note: IFileSystem doesn't have delete method yet, we'll need to add it
      // For now, write empty content
      await this.fileSystem.writeFile(envPath, '');
    }
  }

  /**
   * Convert credentials object to .env file format
   */
  private credentialsToEnvFormat(credentials: Credentials): string {
    const lines: string[] = [
      '# MCP Server Credentials',
      '# Generated by MCP Setter',
      '# Do not commit this file to version control',
      '',
    ];

    for (const [key, value] of Object.entries(credentials)) {
      // Escape special characters in value
      const escapedValue = this.escapeEnvValue(value);
      lines.push(`${key}=${escapedValue}`);
    }

    lines.push(''); // Trailing newline

    return lines.join('\n');
  }

  /**
   * Parse .env file format to credentials object
   */
  private parseEnvFormat(content: string): Credentials {
    const credentials: Credentials = {};
    const lines = content.split('\n');

    for (const line of lines) {
      const trimmed = line.trim();

      // Skip empty lines and comments
      if (!trimmed || trimmed.startsWith('#')) {
        continue;
      }

      // Parse KEY=VALUE
      const equalsIndex = trimmed.indexOf('=');
      if (equalsIndex === -1) {
        continue; // Invalid line
      }

      const key = trimmed.substring(0, equalsIndex).trim();
      const value = trimmed.substring(equalsIndex + 1).trim();

      if (key) {
        credentials[key] = this.unescapeEnvValue(value);
      }
    }

    return credentials;
  }

  /**
   * Escape value for .env format
   */
  private escapeEnvValue(value: string): string {
    // If value contains spaces, newlines, or quotes, wrap in quotes
    if (/[\s"'\n\r]/.test(value)) {
      return `"${value.replace(/"/g, '\\"')}"`;
    }
    return value;
  }

  /**
   * Unescape value from .env format
   */
  private unescapeEnvValue(value: string): string {
    // Remove surrounding quotes if present
    if ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))) {
      const unquoted = value.slice(1, -1);
      return unquoted.replace(/\\"/g, '"').replace(/\\'/g, "'");
    }
    return value;
  }
}
